title: Gantry Documentation
metadata:
    description: 'Gantry Documentation'

author:
  name: RocketTheme
  email: 'devs@gantry.org'

taxonomies: [category,tag]
summary:
  size: 300

github:
  tree: https://github.com/gantry/docs/tree/develop
  commits: https://github.com/gantry/docs/commits/develop/
